import { Bot } from 'lucide-react';

/**
 * Small badge shown on AI columns when the group was analyzed by Ollama (analyzedBy === 'Llm').
 */
export function OllamaBadge() {
  return (
    <span
      data-testid="ollama-badge"
      className="mb-1 inline-flex items-center gap-1 rounded-full bg-violet-100 px-1.5 py-0.5 text-[10px] font-medium text-violet-700 ring-1 ring-violet-300"
      title="Analysis generated by Ollama LLM"
    >
      <Bot size={10} aria-hidden="true" />
      Ollama
    </span>
  );
}
