#requires -Version 5.1
<#
.SYNOPSIS
  One-shot setup for the HotFixAmbulance repo. Wires the pre-commit hook and restores tooling.

.DESCRIPTION
  Steps:
    1. Verify required tools (git, dotnet, node, npm) — warn if missing.
    2. Install `.git/hooks/pre-commit` that delegates to `.claude/hooks/pre-commit.ps1`.
    3. `dotnet restore` if the backend solution exists.
    4. `npm ci` (or `install`) if the frontend package.json exists.

  Re-runnable. Existing files are overwritten only when they would change.

.NOTES
  Phase 0.7 of plan.md.
#>

[CmdletBinding()]
param(
    [switch]$SkipRestore
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

function Assert-Command([string]$name) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        Write-Warning "Required tool not on PATH: $name"
        return $false
    }
    return $true
}

Write-Host '== Tool check ==' -ForegroundColor Cyan
$missingTool = $false
foreach ($t in 'git', 'dotnet', 'node', 'npm') {
    if (-not (Assert-Command $t)) { $missingTool = $true }
}
if (-not ((Get-Command pwsh -ErrorAction SilentlyContinue) -or (Get-Command powershell -ErrorAction SilentlyContinue))) {
    Write-Warning 'Neither pwsh nor powershell found — the git hook cannot run.'
    $missingTool = $true
}
if ($missingTool) {
    Write-Warning 'One or more tools are missing. Install them before running the demo.'
}

Write-Host '== Git hook ==' -ForegroundColor Cyan
$gitDir = (git rev-parse --git-dir).Trim()
$hookPath = Join-Path $gitDir 'hooks\pre-commit'
$psExe = if (Get-Command pwsh -ErrorAction SilentlyContinue) { 'pwsh' } else { 'powershell' }
$hookBody = @"
#!/usr/bin/env sh
# Auto-generated by scripts/bootstrap.ps1 — delegates to .claude/hooks/pre-commit.ps1
exec $psExe -NoLogo -NoProfile -ExecutionPolicy Bypass -File "`$(git rev-parse --show-toplevel)/.claude/hooks/pre-commit.ps1"
"@
$existing = if (Test-Path $hookPath) { Get-Content $hookPath -Raw } else { '' }
if ($existing -ne $hookBody) {
    Set-Content -Path $hookPath -Value $hookBody -NoNewline -Encoding ascii
    Write-Host "  installed -> $hookPath" -ForegroundColor Green
} else {
    Write-Host "  up to date -> $hookPath" -ForegroundColor DarkGray
}

if (-not $SkipRestore) {
    if (Test-Path 'backend\HotFixAmbulance.sln') {
        Write-Host '== dotnet restore ==' -ForegroundColor Cyan
        dotnet restore 'backend\HotFixAmbulance.sln'
    } else {
        Write-Host '== dotnet restore (skipped: backend not scaffolded yet) ==' -ForegroundColor DarkGray
    }

    if (Test-Path 'frontend\package.json') {
        Write-Host '== npm install ==' -ForegroundColor Cyan
        if (Test-Path 'frontend\package-lock.json') {
            npm --prefix frontend ci
        } else {
            npm --prefix frontend install
        }
    } else {
        Write-Host '== npm install (skipped: frontend not scaffolded yet) ==' -ForegroundColor DarkGray
    }
}

Write-Host ''
Write-Host 'Bootstrap complete.' -ForegroundColor Green
